name: ssh
description: SSH and SFTP client for Flutter. Wraps iOS library NMSSH and Android library JSch.
version: 1.0.0
homepage: https://github.com/bogkonstantin/flutter_ssh

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: tech.bogomolov.ssh
        pluginClass: SshPlugin
